# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Python app to Azure Web App - p2-Ana

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      # Configura o ambiente Python para o Flask
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Entra na pasta backend e compacta apenas o que é necessário para o deploy
      - name: Zip artifact for deployment
        run: |
          cd backend
          zip -r ../release.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      # Descompacta o pacote do backend na raiz antes de enviar ao Azure
      - name: Unzip artifact for deployment
        run: unzip release.zip

      # Faz o login usando as suas credenciais originais guardadas no GitHub
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_35839CBC61024A74BAC65B7C49971865 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D21AB7E9CB664D66A3AF6714D73FA64F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_55C7042132B94F2CAAADFB7934EDA18A }}

      # Realiza o Deploy definitivo do Python
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'p2-Ana'
          slot-name: 'Production'
          package: .